Repository SWM-REPL/gifthub-was, pull requests merged in 2023-11, with the labels that each got.

#150 Implement voucher-share cancel api
  src/main/java/org/swmaestro/repl/gifthub/giftcard/repository/GiftcardRepository.java
  src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
  src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java
Labels: 💳 Voucher

#151 Resolve CORS error
  src/main/java/org/swmaestro/repl/gifthub/giftcard/controller/GiftcardController.java
Labels: 🐛 bug, 👮‍♂️ Auth, 💳 Voucher

#152 Update GPT prompt and Handle GPT response time out exception
  src/main/java/org/swmaestro/repl/gifthub/exception/TimeoutException.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/GptService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
  src/main/resources/gpt/question.txt
Labels: 🐛 bug

#153 Add brand-info & product-info to giftcard-response-dto
  src/main/java/org/swmaestro/repl/gifthub/giftcard/dto/GiftcardResponseDto.java
  src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/BrandService.java
  src/test/java/org/swmaestro/repl/gifthub/giftcard/contorller/GiftcardControllerTest.java
Labels: 💳 Voucher

#154 Chagne Giftcard Response from CamelCase
  src/main/java/org/swmaestro/repl/gifthub/giftcard/dto/GiftcardResponseDto.java
  src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/BrandController.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/BrandReadResponseDto.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/BrandService.java
  src/test/java/org/swmaestro/repl/gifthub/giftcard/contorller/GiftcardControllerTest.java
  src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/BrandControllerTest.java
Labels: 🐛 bug, 💳 Voucher

#155 Add 'is-shared' field
  src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherReadResponseDto.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
Labels: 💳 Voucher

#158 Write PULL_REQUEST_TEMPLATE.md (#3)
  src/main/java/org/swmaestro/repl/gifthub/giftcard/controller/GiftcardController.java
Labels: 🐛 bug, 💳 Voucher

#160 Implement GET PresignedURL for get voucher image
  src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherAutoSaveRequestDto.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/GptService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
  src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java
Labels: 💳 Voucher

#161 Solve situations when pending voucher is not created
  src/main/java/org/swmaestro/repl/gifthub/exception/GptResponseException.java
  src/main/java/org/swmaestro/repl/gifthub/exception/TimeoutException.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
  src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java
Labels: 🐛 bug

#162 Collect Sentry errors
  src/main/java/org/swmaestro/repl/gifthub/exception/GptResponseException.java
  src/main/java/org/swmaestro/repl/gifthub/exception/GptTimeoutException.java
  src/main/java/org/swmaestro/repl/gifthub/exception/TimeoutException.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/GptService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
Labels: 🐛 bug

#163 Fix voucher's is-shared
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
Labels: 🐛 bug, 💳 Voucher

#164 Replace PreSigned URL in HTTPS
  src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
Labels: 🐛 bug

#166 Handle error IncorrectResultSizeDataAccessException
  src/main/java/org/swmaestro/repl/gifthub/giftcard/repository/GiftcardRepository.java
  src/main/java/org/swmaestro/repl/gifthub/giftcard/service/GiftcardService.java
Labels: 🐛 bug

#167 fix: add voucher-delete logic
  src/main/java/org/swmaestro/repl/gifthub/auth/controller/UserController.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/repository/VoucherRepository.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
Labels: 👮‍♂️ Auth, 💳 Voucher

#168 Handling NullPointerException
  src/main/java/org/swmaestro/repl/gifthub/auth/service/AppleService.java
  src/main/java/org/swmaestro/repl/gifthub/auth/service/GoogleService.java
  src/main/java/org/swmaestro/repl/gifthub/auth/service/KakaoService.java
  src/main/java/org/swmaestro/repl/gifthub/auth/service/NaverService.java
Labels: 🐛 bug

#170 Divide Firebase Key file depending development and production
  .github/workflows/dev-cd.yml
  .github/workflows/dev-ci.yml
  .github/workflows/prod-cd.yml
  .github/workflows/prod-ci.yml
  .gitignore
  src/main/java/org/swmaestro/repl/gifthub/config/FCMConfig.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java
Labels: 🐛 bug

#171 Handle Production CI test fail
  .github/workflows/prod-ci.yml
Labels: 🐛 bug, ⚙️ CI/CD

#172 Modify barcord column-length
  src/main/java/org/swmaestro/repl/gifthub/auth/controller/UserController.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Voucher.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/repository/VoucherRepository.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
Labels: 💳 Voucher

#174 Set image-url Certainly in etc brand
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
Labels: 🐛 bug, 💳 Voucher

#173 Add is_checked column
  src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherReadResponseDto.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherUpdateRequestDto.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Voucher.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
Labels: 💳 Voucher

#176 Implement voucher-update-response-dto
  src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherUpdateResponseDto.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
  src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java
Labels: 💳 Voucher

#177 Add is-checked field
  src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherUpdateResponseDto.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
Labels: 🐛 bug

#178 Detach and set up with WebClient Config
  .github/workflows/dev-cd.yml
  .github/workflows/dev-ci.yml
  .github/workflows/prod-cd.yml
  .github/workflows/prod-ci.yml
  .gitignore
  src/main/java/org/swmaestro/repl/gifthub/config/FCMConfig.java
  src/main/java/org/swmaestro/repl/gifthub/config/WebClientConfig.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherController.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/dto/VoucherUpdateResponseDto.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/entity/Voucher.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/GptService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/SearchService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/StorageService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
  src/test/java/org/swmaestro/repl/gifthub/vouchers/controller/VoucherControllerTest.java
Labels: 🐛 bug

#180 Handle barcode null error exception
  src/main/java/org/swmaestro/repl/gifthub/auth/repository/UserRepository.java
  src/main/java/org/swmaestro/repl/gifthub/auth/service/UserService.java
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherService.java
Labels: 🐛 bug, 💳 Voucher

#181 Modify return type
  src/main/java/org/swmaestro/repl/gifthub/auth/repository/UserRepository.java
Labels: 🐛 bug

#182 Modify notification message according to exception
  src/main/java/org/swmaestro/repl/gifthub/vouchers/service/VoucherSaveService.java
Labels: 🐛 bug, 📣 Notification
